### PR TITLE
Send text to client, only when it has actually changed from the server

### PR DESCRIPTION
**Pull request by mstahv**

### CODE REVIEW

**Comment by OpenESignForms** [comment]
Thanks Matti.  I'm very new to GIT, having migrated this project from Google Code + SVN.  I think I have your patch incorporated now, and will give it a test along with an update to the latest Vaadin and CKEditor.

**Comment by mstahv** [comment]
Ough, GIT, it is complex, especially in the beginning. I remember the pain when I moved from SVN to GIT. Do yourself a favour and spend a moment with some git tutorial first. Then get some graphical app as you probably won't remember all the commands. Github has its own app, which is pretty simple and easy to use. I use [SourceTree](https://www.sourcetreeapp.com).

**Comment by OpenESignForms** [comment]
Probably confusing git (I've been called that too), but we did bring your patch into our Eclipse and it should be in the 7.10.7 release just uploaded to the vaadin directory.  But I didn't use the pull request as I don't have time now to read up on it all.

**Comment by mstahv** [comment]
Excellent! I'll close this pull request.

**Comment by OpenESignForms** [comment]
If you get a chance, can you look at this new issue 53.  It most likely is the result of the patch for this issue that doesn't always send the updates like it did before:

https://github.com/OpenESignForms/vaadin-ckeditor/issues/53

**Comment by OpenESignForms** [comment]
Thanks again, Matti.  Hope this resolves their issues in 7.10.8.

**Pull request closed without merging**
